### PR TITLE
Add Language: Chinese

### PR DESCRIPTION
**Pull request by qixinynan**
---
name: translate chinese
---

**Description**
Translated EyesGuard into Chinese

**PR Domain**
- Translated into Chinese

### CODE REVIEW

**Comment by Qxiny** [comment]
OK,thank you.



---Original---
From: ***@***.***&gt;
Date: Thu, Oct 21, 2021 14:25 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [avestura/EyesGuard] Add Language: Chinese (PR #33)




 
I'll build and publish this to store as soon as possible.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Sciroccogti** [comment]
> I'll build and publish this to store as soon as possible.

Hmmm has the new version been published? I still cannot find Chinese.😂

**Comment by avestura** [comment]
@Sciroccogti Hi. I tried 3-4 times already to publish the new version but every time either Microsoft Partner platform or my VS didn't work properly. I'll try to do the thing on my old device, I'll let you know how it went.

**Comment by avestura** [comment]
Ok I managed to make another submission. It might take up to three business days for the update to show up in the store (if anything else in the review process by MS doesn't go wrong ofc).

**Pull request merged**
